daviddarnes/alembic

alembic-jekyll-theme.gemspec, assets/search.json
It seems when `\n` is added to the content of a page or post is causes the search functionality to break. So either the javascript isn't handling returns correctly, or we shouldn't be stripping them in the json data. 
In this PR I've gone for the latter, which seems to be working. Leaving the returns how they are seems to be fine for the search.
Issue raised in #61
=> Handling returns in search

_includes/post-categories.html
On the category list page, if a post excerpt has a piece of html crossing over the truncated 60 word threshold it'll cut off the parts of the markup.
Swapping the filters fixes this, however it cuts off markdown instead. Not idea, but better than it's current state
=> Category listing excerpt bug

_includes/nav-header.html, assets/styles.scss
If a theme user hasn't set a `navigation_header` then the default navigation will be used in the header, but the default navigation was missing the button toggle in its markup. This PR applies the nav button toggle using javascript which adds it to any navigation shown in the header.
=> Add nav toggle button to default nav

_sass/sassline-base/_mixins.scss, _sass/sassline-base/_variables.scss
I was getting this
```
LANG=C bundle exec jekyll b _site
Configuration file: /home/stan/src/site/_config.yml
Source: /home/stan/src/site
Destination: /home/stan/src/site/_site
Incremental build: disabled. Enable with --incremental
Generating...
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/styles.scss':
Invalid US-ASCII character "\xE2" on line 27
jekyll 3.6.2 | Error:  Invalid US-ASCII character "\xE2" on line 27
```
This commit changes the two non ascii characters as there are simple replacements.  Another fix would be to put @charset "UTF-8"; at the top of the two files (it seems like they need to be in the relevant file rather than the alembic.scss file, perhaps could be removed from there).
=> replace unicode characters

assets/manifest.json, assets/scripts/sw.js
Move manifest and service worker to subdirectory but use the permalink front matter to place it at the root of the site.
=> Fix: Service Worker generation

README.md, _config.yml, _includes/site-analytics.html, _layouts/default.html
This addition has the ability to enable Google Analytics. The script is contained in a single partial, and is enabled when the user adds their "UA" tracking ID to the configuration file (`_config.yml`) for example:
```
google_analytics: 'UA-XXXXXXXX-1'
```
Addresses #84
=> Feature: Add Google Analytics - #84

README.md, _config.yml, _includes/site-styles.html, _layouts/default.html, assets/styles.scss
This addition has the ability to inline CSS as a single `<style>` block in the `<head>` element. This comes with speed performance perks (depending on the size of your CSS). This can be enabled in the `/_config.yml` with the following option:
``` yml
css_inline: true
```
Addresses #87
=> Feature: Optionally inline CSS - #87

README.md, _config.yml, _layouts/default.html
This isn't really a fix but more of a consistency correction. All keys in the config file are underscore separated (`like_this`), but for some reason I set the service worker as camel case. This pull request brings it back inline, but will cause breaking changes to people using `serviceWorker`. Thankfully it's an enhancement and won't stop the site being used when the site user is online.
=> Fix: Rename serviceWorker to service_worker

_includes/site-analytics.html
Fix for #92: The google analytics html include was referencing an incorrect config key. This should fix it
=> Fix: Correct analytics site config reference #92

_includes/post-pagination.html
Fix for #94: Fixes pagination text so it's labelled as "Newer" and "Older", better representation of what they do / where they go.
=> Fix: Change pagination text #94

README.md, _config.yml, _includes/site-before-end.html, _includes/site-before-start.html, _layouts/default.html
Fixes #111 
This feature adds possibility to include additional Javascript files to the header using `include_header_js` parameter in `/_config.yml`.
`include_header_js` is an array of relative javascript paths to include.
eg:
```
include_header_js:
- my-awesome.js
- my-second-awesome.js
=> [feature] Add feature to include additional JS to header

_includes/nav-header.html, _sass/_theme.scss
Check the browser size on resize and remove mobile toggle styling accordingly, fixes #123
=> [Fix]: Prevent nav being hidden when upscaling browser size

_sass/_settings.scss
As discussed in #127, the `!default` property for `!accentColour` was missed by accident. This pull request fixes the issue.
=> [Fix] added missing default property for accentColour

README.md, _config.yml, _includes/nav-footer.html, _includes/nav-header.html, _includes/nav-share.html, _includes/nav-social.html, alembic-jekyll-theme.gemspec
- Change format of all navigation types
- Remove commented sharing nav items for cleaner presentation
- Ensure items have values before showing them
- Update README.md to ensure sharing nav has been documented correctly
- Remove bundler from dependencies, the gem doesn't need it
Note: This will be a breaking change for navigation and it'll need updating in various places to match the new format of navigation types
=> Update nav formats

assets/manifest.json, assets/scripts/sw.js
layout:none gives a warning in the log of jekyll serve. The correct way
is layout: null. Fixed in manifest.json and sw.js
Fixes #141
=> [FIX] Replace layout: none with layout: null in assets

assets/scripts/sw.js
Fixes:  #152 
add baseurl to post url to fix broken links in github-pages project repos with a non-empty baseurl set in '_config.py'
=> [Fix] Broken Posts in Github-Pages Project Repo

_includes/site-search.html
On the search page there's usage of some keyboard events that are now deprecated and could be removed from future browsers.
- `keyCode` is deprecated in favour of code & key. We use key as we care about the value of the key rather than it's physical position. (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)
- `keypress` is a deprecated event in favour of keydown which represents the same thing but isn't deprecated. (https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event)
The javascript is pretty much the same as before so this should be ok for people to port into their themes that used this as a boilerplate.
=> [Enhancement] Removes deprecated keyCode & keypress usage in search

_layouts/default.html
I had an issue with displaying nordic special characters on my alembic
site. Turns out some browsers don't default to utf8. utf8 seems like a
sane default to me, so I decided to add it and everything works great.
Fixes: #151
=> [Fix] Add meta charset utf8 to default html

_includes/site-favicons.html, assets/manifest.json, assets/scripts/sw.js
The service worker code and site favicon code wasn't including the `baseurl` when it was set, this change fixes that using the `relative_url` filter.
Fixes #162
=> [Fix] Service worker and favicon paths to include baseurl

assets/manifest.json
This make it possible configure `short_name` field in the generated `manifest.json`. 
Documentation to the short_name specification can be found in:
* https://developer.mozilla.org/en-US/docs/Web/Manifest/short_name
* https://w3c.github.io/manifest/#short_name-member
Defaults to use site.title with previous filters (so this is backward compatible).
I've also tweaked how the whitespace is generated to have a more well formatted json file than before.
=> [Enhancement] Make manifest short_name configurable via site.short_name

README.md, _config.yml, assets/manifest.json
- Clean up readme file
- Add `short_name` key documentation
- Add `date_format` to the main config file as a commented example
- Adjust `date_format` documentation
=> [Fix] Add documentation for short_name key, clean up date_format key and docs

README.md, _config.yml, _includes/site-custom-fonts.html, _includes/site-fonts.html, _layouts/default.html, _sass/_settings.scss
Rather than using a css import for the font use async loading using the print media hack + a few other bits and bobs. For more info check out https://csswizardry.com/2020/05/the-fastest-google-fonts/
Also uses font-display: swap so users are able to read the text even though the font hasn't downloaded yet
Finally uses the latest google font api for including the fonts.
I added a TIP comment to _settings.scss so that people customizing this theme know where to go to register their fonts now but let me know if there needs to be any more docs 🙂
=> [Enhancement] Load custom fonts async

_config.yml, alembic-jekyll-theme.gemspec
Jekyll SEO Tags support using the `tagline` attribute to build the `<title>` HTML tag since [v2.7.0](https://github.com/jekyll/jekyll-seo-tag/releases/tag/v2.7.0). Since I need that in a project, and there doesn't seem to be any breaking change, I figured I might as well sugggest a fix ;)
=> [Enhancement] Bump jekyll-seo-tag to 2.7.1 so that we can use `tagline`

_sass/sassline-base/_mixins.scss, _sass/sassline-base/_typography.scss
Addresses https://github.com/daviddarnes/alembic/issues/191
=> Address Issue 191
